### ISSUE TITLE
ToDo List:

### ISSUE THREAD

**Issue by Nachtalb** [Nachtalb/thelounge#1]
- [ ] log search #3664 #4197
- [ ] goto mention
- [ ] load max amount of messages and then recycle dom instead of extending for infinity 
- [ ] postgres message store https://p.gensokyo.re/?ddcfa856b12f8023#KgfSRzceoUPvUpPys8xBKXp8Ddch8iFq6k34xxWSZqv (sqlite search https://p.gensokyo.re/?f9134ace67d1ec0b#6e8pQg47ZSwmt6xifst3q4Jy9dZB1eGnRxs9dPNBdbg3)
---

- [x] reconnect on connection lost symbol click #4189
- [x] auto preview blacklist #4191
- [x] per channel auto preview switch #4191
- [x] per user auto preview switch #4191
- [x] hide empty userdata in join message #4190 https://p.gensokyo.re/?e8225627af477f1b#6w2XF7sLaxv1CmZ2HZaxCRJG6QxvJdC1rQNun3Ghq3FQ
